### ISSUE TITLE
Bio::DB::HTS - includes new Tabix, review code

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/vafCorrect#21]
Hi,

I've noticed you still have code preventing warnings during instantiation of the Tabix module.  The version of Tabix included with Bio::DB::HTS doesn't have this problem.  It also has a changed API so it should be reviewed.

https://github.com/cancerit/cgpVAF/blob/cefaceb9e2198b57d84f85d83ab74e8277c85c38/perl/lib/Sanger/CGP/Vaf/Process/Variant.pm#L25-L29

You should switch to [Bio::DB::HTS::Tabix](http://search.cpan.org/~rishidev/Bio-DB-HTS/lib/Bio/DB/HTS/Tabix.pm).  See [here](https://github.com/cancerit/BRASS/blob/dev/perl/lib/Bio/Brass/Merge.pm) for example.

**Comment by sb43** [comment]
This is now resolved in v4.3.3
