### ISSUE TITLE
Tmp VCF wrongly named in version 5.2.1

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/vafCorrect#36]
There is an issue in version 5.2.1

```bash
This external process failed: cat tmpvaf_{tumor_name}/tmp_*.vcf >>{output_path}_snp_vaf.vcf

ERROR: Error closing pipe from cat at vafCorrect/4.5.2/lib/perl5/Sanger/CGP/Vaf/Data/ReadVcf.pm line 1452.
 at vafCorrect/4.5.2/lib/perl5/Sanger/CGP/Vaf/Data/ReadVcf.pm line 1452.
```

However, tmp vcf file its actually called `temp.vcf` instead of `tmp_*.vcf`:

```bash
ls tmpvaf_{tumor_name}/
progress.out  temp.vcf
```

**Comment by jsmedmar** [comment]
I think this is happening because I had the `CGP_PERLLIBS` variable set and maybe some packages were not built...

**Comment by jsmedmar** [comment]
Never mind, I see what happened. I forgot to update the `PERL5LIB` environment variable and it was picking up the old installation. Sorry for this! please close

**Comment by keiranmraine** [comment]
FYI, you can close tickets you have opened yourself.
