### ISSUE TITLE
add option to filter chromosomes

### ISSUE THREAD

**Issue by sb43** [cancerit/vafCorrect#58]
add an option to filter  non-standard chromosomes as it is taking long time to run for GRCh38 with 3K+ contigs.

**Comment by keiranmraine** [comment]
Should the list of chromosomes to process not be generated by `sort|uniq` the input VCFs chr column.  Then no processing is ever wasted.

**Comment by sb43** [comment]
should only process chrs listed in the input file.

**Comment by sb43** [comment]
This subroutine needs to be fixed :
https://github.com/cancerit/vafCorrect/blob/9ca1de1a5466153e9fe15f14e37796a9df3f77f5/perl/lib/Sanger/CGP/Vaf/Data/ReadVcf.pm#L85

**Comment by keiranmraine** [comment]
Subroutine now follows following logic:

* Only process user specified chrs OR
* Only process `*.bed` file chrs OR
* Collate chrs found in input VCFs

All validated against `*.fai` file.

@sb43 can you confirm this is the expected behaviour?

**Comment by keiranmraine** [comment]
Current block is here:

https://github.com/cancerit/vafCorrect/blob/feature/postDockerCleanup/perl/lib/Sanger/CGP/Vaf/Data/ReadVcf.pm#L87-L110

**Comment by keiranmraine** [comment]
Only processes chrs with data, or provided in chr list.
